<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
<title>SWI-Prolog 9.2.9 Reference Manual: Section 4.10</title><link rel="home" href="index.html">
<link rel="contents" href="Contents.html">
<link rel="index" href="DocIndex.html">
<link rel="summary" href="summary.html">
<link rel="previous" href="delcont.html">
<link rel="next" href="printmsg.html">

<style type="text/css">

/* Style sheet for SWI-Prolog latex2html
*/

dd.defbody
{ margin-bottom: 1em;
}

dt.pubdef, dt.multidef
{ color: #fff;
padding: 2px 10px 0px 10px;
margin-bottom: 5px;
font-size: 18px;
vertical-align: middle;
overflow: hidden;
}

dt.pubdef { background-color: #0c3d6e; }
dt.multidef { background-color: #ef9439; }

.bib dd
{ margin-bottom: 1em;
}

.bib dt
{ float: left;
margin-right: 1.3ex;
}

pre.code
{ margin-left: 1.5em;
margin-right: 1.5em;
border: 1px dotted;
padding-top: 5px;
padding-left: 5px;
padding-bottom: 5px;
background-color: #f8f8f8;
}

div.navigate
{ text-align: center;
background-color: #f0f0f0;
border: 1px dotted;
padding: 5px;
}

div.title
{ text-align: center;
padding-bottom: 1em;
font-size: 200%;
font-weight: bold;
}

div.author
{ text-align: center;
font-style: italic;
}

div.abstract
{ margin-top: 2em;
background-color: #f0f0f0;
border: 1px dotted;
padding: 5px;
margin-left: 10%; margin-right:10%;
}

div.abstract-title
{ text-align: center;
padding: 5px;
font-size: 120%;
font-weight: bold;
}

div.toc-h1
{ font-size: 200%;
font-weight: bold;
}

div.toc-h2
{ font-size: 120%;
font-weight: bold;
margin-left: 2em;
}

div.toc-h3
{ font-size: 100%;
font-weight: bold;
margin-left: 4em;
}

div.toc-h4
{ font-size: 100%;
margin-left: 6em;
}

span.sec-nr
{
}

span.sec-title
{
}

span.pred-ext
{ font-weight: bold;
}

span.pred-tag
{ float: right;
padding-top: 0.2em;
font-size: 80%;
font-style: italic;
color: #fff;
}

div.caption
{ width: 80%;
margin: auto;
text-align:center;
}

/* Footnotes */
.fn {
color: red;
font-size: 70%;
}

.fn-text, .fnp {
position: absolute;
top: auto;
left: 10%;
border: 1px solid #000;
box-shadow: 5px 5px 5px #888;
display: none;
background: #fff;
color: #000;
margin-top: 25px;
padding: 8px 12px;
font-size: larger;
}

sup:hover span.fn-text
{ display: block;
}

/* Lists */

dl.latex
{ margin-top: 1ex;
margin-bottom: 0.5ex;
}

dl.latex dl.latex dd.defbody
{ margin-bottom: 0.5ex;
}

/* PlDoc Tags */

dl.tags
{ font-size: 90%;
margin-left: 5ex;
margin-top: 1ex;
margin-bottom: 0.5ex;
}

dl.tags dt
{ margin-left: 0pt;
font-weight: bold;
}

dl.tags dd
{ margin-left: 3ex;
}

td.param
{ font-style: italic;
font-weight: bold;
}

/* Index */

dt.index-sep
{ font-weight: bold;
font-size: +1;
margin-top: 1ex;
}

/* Tables */

table.center
{ margin: auto;
}

table.latex
{ border-collapse:collapse;
}

table.latex tr
{ vertical-align: text-top;
}

table.latex td,th
{ padding: 2px 1em;
}

table.latex tr.hline td,th
{ border-top: 1px solid black;
}

table.frame-box
{ border: 2px solid black;
}

</style>
</head>
<body style="background:white">
<div class="navigate"><a class="nav" href="index.html"><img src="home.gif" alt="Home"></a>
<a class="nav" href="Contents.html"><img src="index.gif" alt="Contents"></a>
<a class="nav" href="DocIndex.html"><img src="yellow_pages.gif" alt="Index"></a>
<a class="nav" href="summary.html"><img src="info.gif" alt="Summary"></a>
<a class="nav" href="delcont.html"><img src="prev.gif" alt="Previous"></a>
<a class="nav" href="printmsg.html"><img src="next.gif" alt="Next"></a>
</div>
<h2 id="sec:exception"><a id="sec:4.10"><span class="sec-nr">4.10</span> <span class="sec-title">Exception 
handling</span></a></h2>

<a id="sec:exception"></a>

<p>The predicates <a id="idx:catch3:799"></a><a class="pred" href="exception.html#catch/3">catch/3</a> 
and <a id="idx:throw1:800"></a><a class="pred" href="exception.html#throw/1">throw/1</a> 
provide ISO compliant raising and catching of exceptions.

<dl class="latex">
<dt class="pubdef"><span class="pred-tag">[ISO]</span><a id="catch/3"><strong>catch</strong>(<var>:Goal, 
+Catcher, :Recover</var>)</a></dt>
<dd class="defbody">
Behaves as <a id="idx:call1:801"></a><a class="pred" href="metacall.html#call/1">call/1</a> 
if no exception is raised when executing <var>Goal</var>. If an 
exception is raised using <a id="idx:throw1:802"></a><a class="pred" href="exception.html#throw/1">throw/1</a> 
while <var>Goal</var> executes, and the <var>Goal</var> is the innermost 
goal for which <var>Catcher</var> unifies with the argument of <a id="idx:throw1:803"></a><a class="pred" href="exception.html#throw/1">throw/1</a>, 
all choice points generated by <var>Goal</var> are cut, the system 
backtracks to the start of <a id="idx:catch3:804"></a><a class="pred" href="exception.html#catch/3">catch/3</a> 
while preserving the thrown exception term, and <var>Recover</var> is 
called as in <a id="idx:call1:805"></a><a class="pred" href="metacall.html#call/1">call/1</a>.

<p>The overhead of calling a goal through <a id="idx:catch3:806"></a><a class="pred" href="exception.html#catch/3">catch/3</a> 
is comparable to
<a id="idx:call1:807"></a><a class="pred" href="metacall.html#call/1">call/1</a>. 
Recovery from an exception is much slower, especially if the exception 
term is large due to the copying thereof or is decorated with a stack 
trace using, e.g., the library <code>library(prolog_stack)</code> based 
on the
<a id="idx:prologexceptionhook4:808"></a><span class="pred-ext">prolog_exception_hook/4</span> 
hook predicate to rewrite exceptions.</dd>
<dt class="pubdef"><span class="pred-tag">[ISO]</span><a id="throw/1"><strong>throw</strong>(<var>+Exception</var>)</a></dt>
<dd class="defbody">
Raise an exception. The system looks for the innermost <a id="idx:catch3:809"></a><a class="pred" href="exception.html#catch/3">catch/3</a> 
ancestor for which <var>Exception</var> unifies with the <var>Catcher</var> 
argument of the <a id="idx:catch3:810"></a><a class="pred" href="exception.html#catch/3">catch/3</a> 
call. See <a id="idx:catch3:811"></a><a class="pred" href="exception.html#catch/3">catch/3</a> 
for details.

<p>ISO demands that <a id="idx:throw1:812"></a><a class="pred" href="exception.html#throw/1">throw/1</a> 
make a copy of <var>Exception</var>, walk up the stack to a <a id="idx:catch3:813"></a><a class="pred" href="exception.html#catch/3">catch/3</a> 
call, backtrack and try to unify the copy of
<var>Exception</var> with <var>Catcher</var>. SWI-Prolog delays 
backtracking until it actually finds a matching <a id="idx:catch3:814"></a><a class="pred" href="exception.html#catch/3">catch/3</a> 
goal. The advantage is that we can start the debugger at the first 
possible location while preserving the entire exception context if there 
is no matching <a id="idx:catch3:815"></a><a class="pred" href="exception.html#catch/3">catch/3</a> 
goal. This approach can lead to different behaviour if <var>Goal</var> 
and <var>Catcher</var> of <a id="idx:catch3:816"></a><a class="pred" href="exception.html#catch/3">catch/3</a> 
call shared variables. We assume this to be highly unlikely and could 
not think of a scenario where this is useful.<sup class="fn">81<span class="fn-text">I'd 
like to acknowledge Bart Demoen for his clarifications on these matters.</span></sup>

<p>In addition to explicit calls to <a id="idx:throw1:817"></a><a class="pred" href="exception.html#throw/1">throw/1</a>, 
many built-in predicates throw exceptions directly from C. If the <var>Exception</var> 
term cannot be copied due to lack of stack space, the following actions 
are tried in order:

<p>
<ol class="latex">
<li>If the exception is of the form <code>error(Formal, 
ImplementationDefined)</code>, try to raise the exception without the <var>ImplementationDefined</var> 
part.
<li>Try to raise <code>error(<code>resource_error(stack)</code>, global)</code>.
<li>Abort (see <a id="idx:abort0:818"></a><a class="pred" href="toplevel.html#abort/0">abort/0</a>).
</ol>

<p>If an exception is raised in a call-back from C (see <a class="sec" href="foreign.html#sec:12">chapter 
12</a>) and not caught in the same call-back, <a class="func" href="foreigninclude.html#PL_next_solution()">PL_next_solution()</a> 
fails and the exception context can be retrieved using <a class="func" href="foreigninclude.html#PL_exception()">PL_exception()</a>.</dd>
<dt class="pubdef"><a id="catch_with_backtrace/3"><strong>catch_with_backtrace</strong>(<var>:Goal, 
+Catcher, :Recover</var>)</a></dt>
<dd class="defbody">
As <a id="idx:catch3:819"></a><a class="pred" href="exception.html#catch/3">catch/3</a>, 
but if library <code>library(prolog_stack)</code> is loaded and an 
exception of the shape <code>error(Format, Context)</code> is raised
<var>Context</var> is extended with a backtrace. To catch an error and 
print its message including a backtrace, use the following template:

<pre class="code">
:- use_module(library(prolog_stack)).

    ...,
    catch_with_backtrace(Goal, Error,
                         print_message(error, Error)),
    ...,
</pre>

<p>This is good practice for a <em>catch-all</em> wrapper around an 
application. See also <a id="idx:main0:820"></a><a class="pred" href="main.html#main/0">main/0</a> 
from library <code>library(main)</code>.
</dd>
</dl>

<p><h3 id="sec:urgentexceptions"><a id="sec:4.10.1"><span class="sec-nr">4.10.1</span> <span class="sec-title">Urgency 
of exceptions</span></a></h3>

<a id="sec:urgentexceptions"></a>

<p>Under some conditions an exception may be raised as a result of 
handling another exception. Below are some of the scenarios:

<p>
<ul class="latex">
<li>The predicate <a id="idx:setupcallcleanup3:821"></a><a class="pred" href="metacall.html#setup_call_cleanup/3">setup_call_cleanup/3</a> 
calls the cleanup handler as a result of an exception and the cleanup 
handler raises an exception itself. In this case the most <em>urgent</em> 
exception is propagated into the environment.
<li>Raising an exception fails due to lack of resources, e.g., lack of 
stack space to store the exception. In this case a resource exception is 
raised. If that too fails the system tries to raise a resource exception 
without (stack) context. If that fails it will raise the exception
<code>'$aborted'</code>, also raised by <a id="idx:abort0:822"></a><a class="pred" href="toplevel.html#abort/0">abort/0</a>. 
As no stack space is required for processing this atomic exception, this 
should always succeed.
<li>Certain <em>callback</em> operations raise an exception while 
processing another exception or a previous callback already raised an 
exception before there was an opportunity to process the exception. The 
most notable <em>callback</em> subject to this issue are <a id="idx:prologeventhook1:823"></a><span class="pred-ext">prolog_event_hook/1</span> 
(supporting e.g., the graphical debugger), <a id="idx:prologexceptionhook4:824"></a><span class="pred-ext">prolog_exception_hook/4</span> 
(rewriting exceptions, e.g., by adding context) and <a id="idx:printmessage2:825"></a><a class="pred" href="printmsg.html#print_message/2">print_message/2</a> 
when called from the core facilities such as the internal debugger. As 
with
<a id="idx:setupcallcleanup3:826"></a><a class="pred" href="metacall.html#setup_call_cleanup/3">setup_call_cleanup/3</a>, 
the most <em>urgent</em> exception is preserved.
</ul>

<p>If the most urgent exceptions needs to be preserved, the following 
exception ordering is respected, preserving the topmost matching error.

<p>
<ol class="latex">
<li><code>'$aborted'</code> (<a id="idx:abort0:827"></a><a class="pred" href="toplevel.html#abort/0">abort/0</a>)
<li><code>time_limit_exceeded</code> (<a id="idx:callwithtimelimit2:828"></a><span class="pred-ext">call_with_time_limit/2</span>)
<li><code>error(<code>resource_error(Resource)</code>, Context)</code>
<li><code>error(Formal, Context)</code>
<li>All other exceptions
</ol>

<p><b>Note</b> The above resolution is not described in the ISO 
standard. This is not needed either because ISO does not specify
<a id="idx:setupcallcleanup3:829"></a><a class="pred" href="metacall.html#setup_call_cleanup/3">setup_call_cleanup/3</a> 
and does not deal with environment management issues such as (debugger) 
callbacks. Neither does it define <a id="idx:abort0:830"></a><a class="pred" href="toplevel.html#abort/0">abort/0</a> 
or timeout handling. Notably <a id="idx:abort0:831"></a><a class="pred" href="toplevel.html#abort/0">abort/0</a> 
and timeout are non-logical control structures. They are implemented on 
top of exceptions as they need to unwind the stack, destroy choice 
points and call cleanup handlers in the same way. However, the pending 
exception should not be replaced by another one before the intended 
handler is reached. The abort exception cannot be caught, something 
which is achieved by wrapping the <em>cleanup handler</em> of <a id="idx:catch3:832"></a><a class="pred" href="exception.html#catch/3">catch/3</a> 
into
<code>call_cleanup(Handler, abort)</code>.

<p><h3 id="sec:debugexceptions"><a id="sec:4.10.2"><span class="sec-nr">4.10.2</span> <span class="sec-title">Debugging 
and exceptions</span></a></h3>

<a id="sec:debugexceptions"></a>

<p><a id="idx:exceptionsdebugging:833"></a><a id="idx:debuggingexceptions:834"></a>Before 
the introduction of exceptions in SWI-Prolog a runtime error was handled 
by printing an error message, after which the predicate failed. If the 
Prolog flag <a class="flag" href="flags.html#flag:debug_on_error">debug_on_error</a> 
was in effect (default), the tracer was switched on. The combination of 
the error message and trace information is generally sufficient to 
locate the error.

<p>With exception handling, things are different. A programmer may wish 
to trap an exception using <a id="idx:catch3:835"></a><a class="pred" href="exception.html#catch/3">catch/3</a> 
to avoid it reaching the user. If the exception is not handled by user 
code, the interactive top level will trap it to prevent termination.

<p>If we do not take special precautions, the context information 
associated with an unexpected exception (i.e., a programming error) is 
lost. Therefore, if an exception is raised which is not caught using
<a id="idx:catch3:836"></a><a class="pred" href="exception.html#catch/3">catch/3</a> 
and the top level is running, the error will be printed, and the system 
will enter trace mode.

<p>If the system is in a non-interactive call-back from foreign code and 
there is no <a id="idx:catch3:837"></a><a class="pred" href="exception.html#catch/3">catch/3</a> 
active in the current context, it cannot determine whether or not the 
exception will be caught by the external routine calling Prolog. It will 
then base its behaviour on the Prolog flag
<a class="flag" href="flags.html#flag:debug_on_error">debug_on_error</a>:

<p>
<ul class="latex">
<li><i>current_prolog_flag(debug_on_error, false)</i><br>
The exception does not trap the debugger and is returned to the foreign 
routine calling Prolog, where it can be accessed using <a class="func" href="foreigninclude.html#PL_exception()">PL_exception()</a>. 
This is the default.
<li><i>current_prolog_flag(debug_on_error, true)</i><br>
If the exception is not caught by Prolog in the current context, it will 
trap the tracer to help analyse the context of the error.
</ul>

<p>While looking for the context in which an exception takes place, it 
is advised to switch on debug mode using the predicate <a id="idx:debug0:838"></a><a class="pred" href="debugger.html#debug/0">debug/0</a>. 
The hook
<a id="idx:prologexceptionhook4:839"></a><span class="pred-ext">prolog_exception_hook/4</span> 
can be used to add more debugging facilities to exceptions. An example 
is the library <code>library(http/http_error)</code>, generating a full 
stack trace on errors in the HTTP server library.

<p><h3 id="sec:exceptterm"><a id="sec:4.10.3"><span class="sec-nr">4.10.3</span> <span class="sec-title">The 
exception term</span></a></h3>

<a id="sec:exceptterm"></a>

<p><h4 id="sec:generalformofexceptionterm"><a id="sec:4.10.3.1"><span class="sec-nr">4.10.3.1</span> <span class="sec-title">General 
form of the ISO standard exception term</span></a></h4>

<a id="sec:generalformofexceptionterm"></a>

<p>The predicate <a id="idx:throw1:840"></a><a class="pred" href="exception.html#throw/1">throw/1</a> 
takes a single argument, the <em>exception term</em>, and the ISO 
standard stipulates that the exception term be of the form <code>error(Formal, 
Context)</code> with:

<p>
<ul class="latex">
<li><i><var>Formal</var></i><br>
the&lsquo;formal&rsquo;description of the error, as listed in chapter 
7.12.2 pp. 62-63 ("Error classification") of the ISO standard. It 
indicates the <em>error class</em> and possibly relevant <em>error 
context</em> information. It may be a compound term of arity 1,2 or 3 - 
or simply an atom if there is no relevant error context information.

<p>
<li><i><var>Context</var></i><br>
additional context information beyond the one in <var>Formal</var>. If 
may be unset, i.e. a fresh variable, or set to something that hopefully 
will help the programmer in debugging. The structure of <var>Context</var> 
is left unspecified by the ISO Standard, so SWI-Prolog creates it own 
convention (see below).
</ul>

<p>Thus, constructing an error term and throwing it might take this form 
(although you would not use the illustrative explicit naming given here; 
instead composing the exception term directly in a one-liner):

<pre class="code">
Exception = error(Formal, Context),
Context   = ... some local convention ...,
Formal    = type_error(ValidType, Culprit), % for "type error" for example
ValidType = integer,                        % valid atoms are listed in the ISO standard
Culprit   = ... some value ...,
throw(Exception)
</pre>

<p>Note that the ISO standard formal term expresses <em>what should be 
the case</em> or <em>what is the expected correct state</em>, and not
<em>what is the problem</em>. For example:

<p>
<ul class="latex">
<li>If a variable is found to be uninstantiated but should be 
instantiated, the error term is <code>instantiation_error</code>: The 
problem is not that there is an unwanted instantiation, but that the 
correct state is the one with an instantiated variable.

<p>
<li>In case a variable is found to be instantiated but should be 
uninstantiated (because it will be used for output), the error term is
<code>uninstantiation_error(Culprit)</code>: The problem is not that 
there is lack of instantiation, but that the correct state is the one 
which
<var>Culprit</var> (or one of its subterms) is more uninstantiated than 
is the case.

<p>
<li>If you try to disassemble an empty list with <a id="idx:compoundnamearguments3:841"></a><a class="pred" href="manipterm.html#compound_name_arguments/3">compound_name_arguments/3</a>, 
the error term is <code>type_error(compound,[])</code>. The problem is 
not that <code><code>[]</code></code> is (erroneously) a compound term, 
but that a compound term is expected and <code><code>[]</code></code> 
does not belong to that class.
</ul>

<p><h4 id="sec:throwsfromuserpreds"><a id="sec:4.10.3.2"><span class="sec-nr">4.10.3.2</span> <span class="sec-title">Throwing 
exceptions from applications and libraries</span></a></h4>

<a id="sec:throwsfromuserpreds"></a>

<p>User predicates are free to choose the structure of their <em>exception 
term</em>s (i.e., they can define their own conventions) but <em>should</em> 
adhere to the ISO standard if possible, in particular for libraries.

<p>Notably, exceptions of the shape <code>error(Formal,Context)</code> 
are recognised by the development tools and therefore expressing 
unexpected situations using these exceptions improves the debugging 
experience.

<p>In SWI-Prolog, the second argument of the exception term, i.e., the
<var>Context</var> argument, is generally of the form
<code>context(Location, Message)</code>, where:

<p>
<ul class="latex">
<li><i><var>Location</var></i><br>
describes the execution context in which the exception occurred. While 
the <var>Location</var> argument may be specified as a predicate 
indicator (<var>Name</var>/<var>Arity</var>), it is typically filled by 
the <code>library(prolog_stack)</code> library. This library recognises 
uncaught errors or errors caught by <a id="idx:catchwithbacktrace3:842"></a><a class="pred" href="exception.html#catch_with_backtrace/3">catch_with_backtrace/3</a> 
and fills the
<var>Location</var> argument with a <em>backtrace</em>.

<p>
<li><i><var>Message</var></i><br>
provides an additional description of the error or can be left as a 
fresh variable if there is nothing appropriate to fill in.
</ul>

<p>ISO standard exceptions can be thrown via the predicates exported 
from <code>library(error)</code>. Termwise, these predicates look 
exactly like the
<var>Formal</var> of the ISO standard error term they throw:

<p>
<ul class="latex">
<li><a id="idx:instantiationerror1:843"></a><a class="pred" href="error.html#instantiation_error/1">instantiation_error/1</a> 
(the argument is not used: ISO specifies no argument)
<li><a id="idx:uninstantiationerror1:844"></a><a class="pred" href="error.html#uninstantiation_error/1">uninstantiation_error/1</a>
<li><a id="idx:typeerror2:845"></a><a class="pred" href="error.html#type_error/2">type_error/2</a>
<li><a id="idx:domainerror2:846"></a><a class="pred" href="error.html#domain_error/2">domain_error/2</a>
<li><a id="idx:existenceerror2:847"></a><a class="pred" href="error.html#existence_error/2">existence_error/2</a>
<li><a id="idx:existenceerror3:848"></a><a class="pred" href="error.html#existence_error/3">existence_error/3</a> 
(a SWI-Prolog extension that is not ISO)
<li><a id="idx:permissionerror3:849"></a><a class="pred" href="error.html#permission_error/3">permission_error/3</a>
<li><a id="idx:representationerror1:850"></a><a class="pred" href="error.html#representation_error/1">representation_error/1</a>
<li><a id="idx:resourceerror1:851"></a><a class="pred" href="error.html#resource_error/1">resource_error/1</a>
<li><a id="idx:syntaxerror1:852"></a><a class="pred" href="error.html#syntax_error/1">syntax_error/1</a>
</ul>

<p></body></html>